# Generated by Django 4.1 on 2022-11-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMissions',
            new_name='DailyMission',
        ),
    ]
